# This file was generated by 'rake generate_secret_token', and should
# not be made visible to public.
# If you have a load-balancing Redmine cluster, you will need to use the
# same version of this file on each machine. And be sure to restart your
# server when you modify this file.
#
# Your secret key for verifying cookie session data integrity. If you
# change this key, all old sessions will become invalid! Make sure the
# secret is at least 30 characters and all random, no regular words or
# you'll be exposed to dictionary attacks.
RedmineApp::Application.config.secret_token = '86df250685546b7f2a0228c9fcef937836d0ec714610e42f10f333747a75a8c156929307764c18d986df250685546b7f2a0228c9fcef937836d0ec714610e42f10f333747a75a8c156929307764c18d9'
